version: '3.8'
services:
  gitlab-server:
    image: 'gitlab/gitlab-ce'
    container_name: 'my-gitlab-server'
    ports:
      - '8000:80'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'W@qas123123123'
        puma['worker_processes'] = 0
    volumes:
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'